name: restful
version: 0.3.0
authors:
- Dan Schultz <dan@mixbook.com>
- Anton Astashov <anton@mixbook.com>
description: A package for working with restful web services.
homepage: http://www.github.com/mixbook/restful.dart
dependencies:
  logging: '>=0.5.13'
dev_dependencies:
  browser: any
  logging_handlers: '>=0.5.0'
  unittest: any
